language: node_js
notifications:
  email: false
  slack:
    rooms:
      secure: bsDNPmqrGTQhysajh/gw4vzbmPZTlXLNT3FnAtkwjXIS/cQzUkJxbCtArXtEVoKFQVZuhVV7EOrHuoGM80FQLj/PrFvml16w6ZdGSKmShrME4QDrl8l403ip3xfGWC9KXTPCGh7/IA4EK+Q/naamBe2DaRNXMIIP8cnppTecP0mhFZ7Ctqgl/V+SlFbDVz4sO7RgQwKOtVd9/NOibCmKaldWMGVfC7HMh6d+YR+WM3VSUIpLqC6AeLtZ8yKGATTDabuk6Dmmjp12ODEKFxgNA5KCJ3WybTij3e+WlmApdLN7nMeV27GDYt6ydyBhE2UreAJtc1LmS7OCcC144M6FCMS+G6RX3p7vLPGDwI5v4F2TxOcMQkM5MEF8stBZW3sDCsTUZriEzr2YBUcBzygo+1yfldYFn2n9QCy1IU0sunV09ru792Y3+ckIx0XHiSw+zCRe2V/SJrCZgAfdeavusWEvCLqQD42KATif14ph1kQvQxbOL2WZCOqgcYJqY+lDsZtNiizo7KdPnYKnMJ1v0/1H2VnP3JvKkO9n7X2NXcYl1iVasenh0CKjCEqZadqAqceIv3HDmn43AMMDz0ecJMAzAN3Jk5mZGQt2GazzCCaL9HLvBf1ruptG4P4qHc4G8IS0gqITmrAMOQH6INmMBHGslh3FkSq3yjxyRsnjjfA=
